// components/litzComponent.tsx
import { FC, useCallback, useEffect, useMemo, useState } from "react";
import styled from "styled-components";

const fallbackImageId = "litz1.gif";

export const LitzComponent: FC<{
  name?: string;
  prefix?: string;
  imageId?: string;
}> = ({ name = "🤦", imageId: initialImageId, prefix: originalPrefix }) => {
  const litzMessage = useMemo(getMessage, [name, originalPrefix]);
  const [imageId, setImageId] = useState(initialImageId);
  const initializeImageIdCallback = useCallback(initializeImageId, [
    initialImageId,
    setImageId,
  ]);

  useEffect(() => {
    initializeImageIdCallback().then(null);
  }, [initializeImageIdCallback]);

  if (!imageId) {
    return null;
  }

  return (
    <Host>
      <h1>{litzMessage}</h1>
      <LitzImage
        src={`/assets/litzes/${imageId}`}
        onError={() => setImageId(fallbackImageId)}
      />
      <br />
      <LinkContainer>
        <a href={getPermalink()}>Permalink</a>
      </LinkContainer>
    </Host>
  );

  function getMessage() {
    if (name === "🤦" || name === "👩") {
      return `S'hät wieder ${name == "👩" ? "eini" : "eine"} glitzt!`;
    }

    if (name === "mich") {
      return "Mich häts glitzt!";
    }

    const prefix = originalPrefix == "👩" ? "D'" : originalPrefix || "Dä";
    return `${startWithUpper(prefix)} ${startWithUpper(name)} häts glitzt!`;
  }

  function getPermalink() {
    return originalPrefix
      ? `/${originalPrefix}/${name}/${imageId}`
      : `/${name}/${imageId}`;
  }

  async function initializeImageId() {
    if (initialImageId) {
      return;
    }

    try {
      setImageId(await fetch("/server/random-litz.php").then((r) => r.json()));
    } catch (err) {
      console.error(`Failed to load image: ${JSON.stringify(err)}`);
      setImageId(fallbackImageId);
    }
  }
};

function startWithUpper(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

const Host = styled.div`
  text-align: center;
`;

const LitzImage = styled.img`
  width: 480px;
  height: 307.848px;
  left: 0px;
  top: 0px;
`;

const LinkContainer = styled.span`
  font-size: 0.75rem;
`;

// src/app/litz.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from "@angular/router";
import { Http, Response } from "@angular/http";

@Component({
  templateUrl: './litz.component.html'
})
export class LitzComponent implements OnInit {

  private static facePalmUniCode: string = "🤦";

  public litzMessage: string;
  public imageName: string;
  public name: string;
  public permaLink: string;
  public baseUrl: string;
  public showUploadStuff: boolean;
  
  public constructor(private route: ActivatedRoute, private http: Http) {
  }

  public ngOnInit(): void {
    this.route.params.subscribe(params => {
      this.setMessage(params["name"]);
      let urlImageName: string = params["litzImageName"];
          if (!urlImageName) {
            this.getRandomImage();
          } else {
            this.setImage(urlImageName);
          }
    });
  }

  private setMessage(name?: string): void {
    this.name = name;
    if (name && name != LitzComponent.facePalmUniCode) {
      if (name != "mich") {
        this.litzMessage = `Dä ${this.capitalizeFirstLetter(name)} häts glitzt!`;
      } else {
        this.litzMessage = "Mich häts glitzt!";
      }
    } else {
      this.litzMessage = "S'hät wieder eine glitzt!";
    }

    this.baseUrl = `${document.location.origin}/${this.name || LitzComponent.facePalmUniCode}`;
  }

  private capitalizeFirstLetter(value: string): string {
    return value.charAt(0).toUpperCase() + value.slice(1);
  }

  public getRandomImage(): void {
    this.http
        .get("/server/random-litz.php")
        .subscribe(res => this.setImage(res.json()),
                   error => this.setFallbackImage());
  }

  private setImage(imageName: string) {
    this.imageName = imageName;
    this.permaLink = `${this.baseUrl}/${imageName}`
  }

  private setFallbackImage(): void {
    this.setImage("litz1.gif");
  }
}

<div style="text-align:center">
  <h1>
    {{litzMessage}}!
  </h1>
  <img *ngIf="imageName"
       src="./assets/litzes/{{imageName}}"
       style="width: 480px; height: 307.848px; left: 0px; top: 0px;"
       (error)="getRandomImage()" />
  <br />
  <span style="font-size: 0.75rem">
    <a *ngIf="permaLink" href="{{permaLink}}">
      Permalink
    </a>
    |
    <a href="javascript:void(0)" (click)="showUploadStuff = !showUploadStuff">
      Würg neui Litz Bilder ine
    </a>
  </span>
</div>

<div *ngIf="showUploadStuff">
  <litz-upload [baseUrl]="baseUrl"></litz-upload>
</div>
